default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: interview_assistant_development

test:
  <<: *default
  database: interview_assistant_test
